spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/organization
    username: postgres
    password: ${PASSWORD_DB}
    initialization-mode: always
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: organization
    schema: public
    username: postgres
    password: ${PASSWORD_DB}
  aws:
    region: us-east-1
    session:
      name:${AWS_SESSION_NAME}
    dynamodb:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-access-key: ${AWS_SECRET_ACCESS_KEY}
      role: ${DYNAMO_ROLE}
      endpoint: ${DYNAMO_ENDPOINT}
LOG_LEVEL: debug