server:
  port: 8080
spring:
  application:
    name: "franchise"
  devtools:
    add-properties: false
  profiles:
    include: "${ENVIRONMENT}"
    active: "${ENVIRONMENT}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
aws:
  dynamodb:
    endpoint: "http://localhost:8000"
